services:
  postgres:
    image: postgres:16-alpine
    # mem_limit: 512m
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_SOURCE=${DB_SOURCE}
    depends_on:
      - postgres
volumes:
  data-volume:
